-- MySQL Script generated by MySQL Workbench
-- Sun Oct 22 23:00:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ProjetoMaromba
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProjetoMaromba` ;

-- -----------------------------------------------------
-- Schema ProjetoMaromba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoMaromba` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoMaromba` ;

-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `valorProduto` VARCHAR(45) NOT NULL,
  `marcaProduto` VARCHAR(45) NOT NULL,
  `pesoProduto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`LevelLogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`LevelLogin` (
  `idLevelLogin` INT NOT NULL AUTO_INCREMENT,
  `nameLevel` VARCHAR(15) NULL,
  PRIMARY KEY (`idLevelLogin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Login` (
  `idLogin` INT NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(60) NOT NULL,
  `Password` VARCHAR(25) NULL,
  `idLevelLogin` INT NOT NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_LevelLogin1_idx` (`idLevelLogin` ASC),
  CONSTRAINT `fk_Login_LevelLogin1`
    FOREIGN KEY (`idLevelLogin`)
    REFERENCES `ProjetoMaromba`.`LevelLogin` (`idLevelLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nomeUsuario` VARCHAR(60) NOT NULL,
  `cpfUsuario` VARCHAR(14) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `telefoneUsuario` VARCHAR(20) NOT NULL,
  `idLogin` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Login1_idx` (`idLogin` ASC),
  CONSTRAINT `fk_Usuario_Login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `ProjetoMaromba`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Dados Bancarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Dados Bancarios` (
  `idDadosBancarios` INT NOT NULL AUTO_INCREMENT,
  `numeroCartao` VARCHAR(16) NOT NULL,
  `nomeCartao` VARCHAR(60) NOT NULL,
  `vencimentoCartao` DATE NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDadosBancarios`),
  INDEX `fk_Dados Bancarios_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Dados Bancarios_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProjetoMaromba`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Uf` (
  `idUf` INT NOT NULL AUTO_INCREMENT,
  `UnidadeFederativa` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idUf`))
ENGINE = InnoDB;


INSERT INTO uf (UnidadeFederativa, Sigla) VALUES
('Acre', 'AC'),
('Alagoas', 'AL'),
('Amapá', 'AP'),
('Amazonas', 'AM'),
('Bahia', 'BA'),
('Ceará', 'CE'),
('Distrito Federal', 'DF'),
('Espírito Santo', 'ES'),
('Goiás', 'GO'),
('Maranhão', 'MA'),
('Mato Grosso', 'MT'),
('Mato Grosso do Sul', 'MS'),
('Minas Gerais', 'MG'),
('Pará', 'PA'),
('Paraíba', 'PB'),
('Paraná', 'PR'),
('Pernambuco', 'PE'),
('Piauí', 'PI'),
('Rio de Janeiro', 'RJ'),
('Rio Grande do Norte', 'RN'),
('Rio Grande do Sul', 'RS'),
('Rondônia', 'RO'),
('Roraima', 'RR'),
('Santa Catarina', 'SC'),
('São Paulo', 'SP'),
('Sergipe', 'SE'),
('Tocantins', 'TO');

-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(45) NOT NULL,
  `idUf` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_Cidade_Uf1_idx` (`idUf` ASC),
  CONSTRAINT `fk_Cidade_Uf1`
    FOREIGN KEY (`idUf`)
    REFERENCES `ProjetoMaromba`.`Uf` (`idUf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `nomeEndereco` VARCHAR(100) NOT NULL,
  `numeroEndereco` VARCHAR(10) NOT NULL,
  `cepEndereco` VARCHAR(8) NOT NULL,
  `Referencia` VARCHAR(100) NULL,
  `idCidade` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Endereco_Cidade1_idx` (`idCidade` ASC),
  INDEX `fk_Endereco_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `ProjetoMaromba`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProjetoMaromba`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Transportadora` (
  `idTransportadora` INT NOT NULL AUTO_INCREMENT,
  `nomeTransportadora` VARCHAR(45) NOT NULL,
  `telefoneTransportadora` VARCHAR(20) NOT NULL,
  `cnpfTransportadora` VARCHAR(20) NOT NULL,
  `situacaoTransportadora` VARCHAR(20) NOT NULL,
  `idLogin` INT NOT NULL,
  PRIMARY KEY (`idTransportadora`),
  INDEX `fk_Transportadora_Login1_idx` (`idLogin` ASC),
  CONSTRAINT `fk_Transportadora_Login1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `ProjetoMaromba`.`Login` (`idLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `dataPedido` DATE NOT NULL,
  `enderecoPedido` VARCHAR(45) NOT NULL,
  `statusPedido` VARCHAR(45) NOT NULL,
  `dataEntregaPedido` DATE NULL,
  `idUsuario` INT NOT NULL,
  `idTransportadora` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Pedido_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProjetoMaromba`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `ProjetoMaromba`.`Transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Pedido_Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Pedido_Produto` (
  `idPedido` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `idProduto`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`idProduto` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`idPedido` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `ProjetoMaromba`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ProjetoMaromba`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoMaromba`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoMaromba`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(20) NOT NULL,
  `idUsuario` INT NULL,
  `idTransportadora` INT NULL,
  PRIMARY KEY (`idTelefone`),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  INDEX `fk_Telefone_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Telefone_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_Telefone_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ProjetoMaromba`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Telefone_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `ProjetoMaromba`.`Transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
